api_platform:
    title: 'My Booking API'
    version: '1.0.0'
    description: 'API for house bookings'
    openapi:
        contact:
            name: 'Your Name'
            email: 'you@example.com'
    formats:
        jsonld: { mime_types: ['application/ld+json'] }
        json:   { mime_types: ['application/json'] }
    patch_formats:
        json: { mime_types: ['application/merge-patch+json'] }
    enable_swagger_ui: true
    enable_re_doc: true