security:
    password_hashers:
        App\Entity\User: 'auto'
        App\Entity\AdminUser: 'auto'

    providers:
        app_user_provider:
            id: App\Security\CsvUserProvider
        admin_user_provider:
            entity:
                class: App\Entity\AdminUser
                property: phone

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        admin:
            lazy: true
            provider: admin_user_provider
            form_login:
                login_path: admin_login
                check_path: admin_login
            logout:
                path: admin_logout

        main:
            lazy: true
            provider: app_user_provider
            json_login:
                check_path: api_login
            logout:
                path: api_logout

    access_control:
        - { path: ^/admin/login, roles: PUBLIC_ACCESS }
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/api, roles: IS_AUTHENTICATED_FULLY }