parameters:
    app.data_dir: '%kernel.project_dir%/var/data'

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    App\Service\CsvHouseService:
        arguments:
            $dataDir: '%app.data_dir%'

    App\Service\CsvBookingService:
        arguments:
            $dataDir: '%app.data_dir%'

    App\Service\UserService:
        arguments:
            $userCsvPath: '%app.data_dir%/users.csv' 